# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Catalin Lupau
title: Machine Learning Engineer & Software Developer
email: catalin.lupau10.workrelated@gmail.com
phone: "0031616931661"
# website: www.github.com/sproogen/resume-theme

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  catalinlup
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: catalinlup
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Catalin Lupau and I am a machine learning engineer with a strong background in software development. I can develop and train deep learning models as well as build full-stack software applications. 
  
  My specialization is <mark>natural language processing</mark>. I have spent 9 months doing research in the field neural search, which consists of applying natural language processing (NLP) to search engines.
content:
  - title: Noteworthy Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Development of quantization algorithm for neural search
        link: http://resolver.tudelft.nl/uuid:f6fa94f8-ca16-4362-8858-08ca8f0dcd21
        link_text: View research thesis
        # additional_links:
        #   - title:  sproogen/modern-resume-theme
        #     icon: fab fa-github
        #     url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        # quote: >
        #   This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I took part in 9 months of intensive research as part of TU Delft's Web Information Systems department. The aim of the research was the development of a novel vector quantization algorithm that reduces the size of neural dense indices used by modern search engines and question-answering systems. The project was successful and I am in the process of writing a scientific paper based on it to be published in an academic journal.
      - layout: top-middle
        title: Container Twistlock Handling Robot
        link: github.com/sproogen
        link_text: View project video
        description: |
          The project consisted of developing a fully functional robot prototype to handle container twistlocks. The project was done in a team of 5 other students with various backgrounds and it involved both designing and building the robot. My role as a computer scientist was training the computer vision model to detect the twistlocks, implementing the low-level control software that would run the robot, aswellasawebapplicationfortheuserstointeractwiththerobot. The project was done as part of TU Delft's robotics minor in collaboration with Siemens, in an internship format.
      
      - layout: top-middle
        title: Red teaming large language models
        link: https://aclanthology.org/2023.artofsafety-1.2
        link_text: View published paper
        description: |
          This was a research project done in a small team and it consisted of evaluating the effectiveness of different techniques used to hack large language models into generating harmful content by bypassing their safety measures. In addition to that, we came up with and evaluated techniques that would help the large language models better resist the attacks. The outcome of the project was a dataset of malicious and protective prompts, as well as a scientific paper presenting the associated experimental results. Our paper was among the first papers on red teaming large language models and it was published in a scientific conference about AI safety.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Docklab
        sub_title: AI & Software Engineer
        caption: September 2022 - Present
        description: | # this will include new lines to allow paragraphs
            My responsibilities at Docklab were both as an AI engineer and a full-stack software developer, based on the company's necessities. As Docklab is a venture studio, I took up high-risk projects and developed them to the point that they could be validated with clients and turned into Docklab spin-offs. This meant that I had the opportunity to work and gain experience in training machine learning / deep learning models (using scikit-learn, PyTorch, Huggingface), doing backend development (using FastAPI and Flask), as well as frontend development (using Typescript + React). I was occasionally responsible for DevOps, specifically configuring automatic deployment and testing in GitHub Actions and Terraform. In addition to all of these, I would set up our production environments, which led to me gaining experience using Google Cloud solutions, such as Vertex AI or Cloud Run. In summary, since Docklab is a small company taking up diverse software projects, I was lucky enough to gain real-life experience applying many technologies in a wide range of contexts.
      
      - layout: left
        title: Siemens
        sub_title: Robotics Developer Intern
        caption: September 2021 - January 2022
        description: |
            As part of a team of 6 students (2 mechanical engineers, 1 electrical engineer, 1 industrial designer, and 2 computer scientists, including myself), I worked on creating a robot that handles container twistlocks in a harbor environment. The project involved design and implementation (creating a fully functional prototype of the robot). My responsibilities were as a machine learning engineer and a general full-stack software developer. I had to write both low-level control software running on the robot, as well as a high-level web application used to control it. In addition to this, I trained YOLOv4-based computer-vision model to detect twistlocks. The project was done as part of the university's robotics minor in collaboration with Siemens.

      - layout: left
        title: ScenWise
        sub_title: Software Developer Intern
        caption: April 2021 - July 2021
        description: |
          During my time as a software developer at ScenWise I learned development processes (e.g. AGILE development) and best practices, while creating a traffic management tool using Spring Boot and React. I wrote clean, well-structured and well-tested code for the project, while simultanously acting as a SCRUM master for my team.

      - layout: left
        title: TU Delft
        sub_title: Teaching Assistant
        caption: November 2020 - February 2021
        description: |
          As a teaching assistant for my university I assisted students with lab assignments and answered questions regarding the material for the Algorithms and Data Structures course. My experience as a university teaching assistant proved very useful later in my career. It taught me to explain highly complex concepts in simple terms, which is often necessary when working with people that have a different educational background than yours.

      - layout: left
        title: Coder Dojo
        sub_title: Robotics Mentor
        caption: September 2016 - July 2019
        description: |
          My role as a robotics mentor at Coder Dojo was to assist club members (younger high school or middle school students) with their Aruduino or Raspberry Pi robotics projects. In addition to that, I engaged in computer science projects with other mentor and club members.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: TU Delft
        caption: September 2022 - June 2024
        sub_title: MSc Computer Science (AI Track) - Cum Laude
        quote: >
          The Delft University of Technology (TU Delft; Dutch: Technische Universiteit Delft) is the oldest and largest Dutch public technical university, located in Delft, The Netherlands. It specializes in engineering, technology, computing, design, and natural sciences.
        description: | # this will include new lines to allow paragraphs
          During my time following a masters degree at TU Delft, I have specialized in Aritificial Intelligence. I have developed deep knwoledge in key areas such as <mark>Statistics & Probability Theory</mark>, <mark>Machine Learning</mark> and <mark>Deep Learning</mark>, which are essential for any well-rounded AI engineer. 
          
          On top of the above, I have developed the ability to comprehend and perform state-of-the-art research, as well as apply the gained insights in products. Since AI is a rapidly developing field, I stronly believe that my ability to stay in touch with the latest research is my key stength.

      - layout: left
        title: TU Delft
        caption: September 2019 - July 2022
        sub_title: BSc Computer Science & Engineering - Cum Laude
        description: | # this will include new lines to allow paragraphs
          My bachelor degree trained me to become a good software engineer, while at the same time providing me with basic machine learning knowledge. 
          
          During my bachelor I had the opportunity to take part in many software development team projects and internships, which gave me practical experience and helped me develop leadership skills, as well as the ability to work well in diverse international environments.
      
      - layout: left
        title: C.N. Emanuil Gojdu, Oradea, Romania
        caption: September 2015 - June 2019
        sub_title: High School Diploma
        description: |
          During my high school years I always strived for excellence, which resulted in me graduating as a valedictorian (highest average grade in my generation).

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my passion for AI and software engineering some of my other interests and hobbies are:
      - Science Fiction (I am a big Star Trek fan ☺️)
      - Reading and having debates about philosophy, macro-economics or geopolitics
      - Pursuing a healthy diet and training


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
